version: '3.8'

services:
  web:
    build: ..
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/opt/src/mailing/
    expose:
      - 8000
    env_file:
      - ../.env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: mailing

  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      - web